// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registry.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 port = 1;</code>
   * @return The port.
   */
  int getPort();
}
