// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

/**
 * Protobuf type {@code registry.RegistryMessage}
 */
@com.google.protobuf.Generated
public final class RegistryMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:registry.RegistryMessage)
    RegistryMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RegistryMessage");
  }
  // Use RegistryMessage.newBuilder() to construct.
  private RegistryMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RegistryMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.bobliu.rpc.proto.RegistryMessage.class, tech.bobliu.rpc.proto.RegistryMessage.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REGISTER(1),
    HEARTBEAT(2),
    SUBSCRIBE(3),
    RESPONSE(4),
    SERVICE_LIST(5),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return REGISTER;
        case 2: return HEARTBEAT;
        case 3: return SUBSCRIBE;
        case 4: return RESPONSE;
        case 5: return SERVICE_LIST;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int REGISTER_FIELD_NUMBER = 1;
  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   * @return Whether the register field is set.
   */
  @java.lang.Override
  public boolean hasRegister() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   * @return The register.
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.RegisterRequest getRegister() {
    if (payloadCase_ == 1) {
       return (tech.bobliu.rpc.proto.RegisterRequest) payload_;
    }
    return tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
  }
  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.RegisterRequestOrBuilder getRegisterOrBuilder() {
    if (payloadCase_ == 1) {
       return (tech.bobliu.rpc.proto.RegisterRequest) payload_;
    }
    return tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 2;
  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   * @return Whether the heartbeat field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   * @return The heartbeat.
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.HeartbeatRequest getHeartbeat() {
    if (payloadCase_ == 2) {
       return (tech.bobliu.rpc.proto.HeartbeatRequest) payload_;
    }
    return tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
  }
  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
    if (payloadCase_ == 2) {
       return (tech.bobliu.rpc.proto.HeartbeatRequest) payload_;
    }
    return tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
  }

  public static final int SUBSCRIBE_FIELD_NUMBER = 3;
  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   * @return Whether the subscribe field is set.
   */
  @java.lang.Override
  public boolean hasSubscribe() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   * @return The subscribe.
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.SubscribeRequest getSubscribe() {
    if (payloadCase_ == 3) {
       return (tech.bobliu.rpc.proto.SubscribeRequest) payload_;
    }
    return tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
  }
  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.SubscribeRequestOrBuilder getSubscribeOrBuilder() {
    if (payloadCase_ == 3) {
       return (tech.bobliu.rpc.proto.SubscribeRequest) payload_;
    }
    return tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
  }

  public static final int RESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   * @return The response.
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.RegistryResponse getResponse() {
    if (payloadCase_ == 4) {
       return (tech.bobliu.rpc.proto.RegistryResponse) payload_;
    }
    return tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
  }
  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.RegistryResponseOrBuilder getResponseOrBuilder() {
    if (payloadCase_ == 4) {
       return (tech.bobliu.rpc.proto.RegistryResponse) payload_;
    }
    return tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
  }

  public static final int SERVICE_LIST_FIELD_NUMBER = 5;
  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   * @return Whether the serviceList field is set.
   */
  @java.lang.Override
  public boolean hasServiceList() {
    return payloadCase_ == 5;
  }
  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   * @return The serviceList.
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceList getServiceList() {
    if (payloadCase_ == 5) {
       return (tech.bobliu.rpc.proto.ServiceList) payload_;
    }
    return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
  }
  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceListOrBuilder getServiceListOrBuilder() {
    if (payloadCase_ == 5) {
       return (tech.bobliu.rpc.proto.ServiceList) payload_;
    }
    return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (tech.bobliu.rpc.proto.RegisterRequest) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (tech.bobliu.rpc.proto.HeartbeatRequest) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (tech.bobliu.rpc.proto.SubscribeRequest) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (tech.bobliu.rpc.proto.RegistryResponse) payload_);
    }
    if (payloadCase_ == 5) {
      output.writeMessage(5, (tech.bobliu.rpc.proto.ServiceList) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (tech.bobliu.rpc.proto.RegisterRequest) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (tech.bobliu.rpc.proto.HeartbeatRequest) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (tech.bobliu.rpc.proto.SubscribeRequest) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (tech.bobliu.rpc.proto.RegistryResponse) payload_);
    }
    if (payloadCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (tech.bobliu.rpc.proto.ServiceList) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.bobliu.rpc.proto.RegistryMessage)) {
      return super.equals(obj);
    }
    tech.bobliu.rpc.proto.RegistryMessage other = (tech.bobliu.rpc.proto.RegistryMessage) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getRegister()
            .equals(other.getRegister())) return false;
        break;
      case 2:
        if (!getHeartbeat()
            .equals(other.getHeartbeat())) return false;
        break;
      case 3:
        if (!getSubscribe()
            .equals(other.getSubscribe())) return false;
        break;
      case 4:
        if (!getResponse()
            .equals(other.getResponse())) return false;
        break;
      case 5:
        if (!getServiceList()
            .equals(other.getServiceList())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + REGISTER_FIELD_NUMBER;
        hash = (53 * hash) + getRegister().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeat().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SUBSCRIBE_FIELD_NUMBER;
        hash = (53 * hash) + getSubscribe().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + SERVICE_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getServiceList().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.bobliu.rpc.proto.RegistryMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.bobliu.rpc.proto.RegistryMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.RegistryMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.bobliu.rpc.proto.RegistryMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registry.RegistryMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registry.RegistryMessage)
      tech.bobliu.rpc.proto.RegistryMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.bobliu.rpc.proto.RegistryMessage.class, tech.bobliu.rpc.proto.RegistryMessage.Builder.class);
    }

    // Construct using tech.bobliu.rpc.proto.RegistryMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (registerBuilder_ != null) {
        registerBuilder_.clear();
      }
      if (heartbeatBuilder_ != null) {
        heartbeatBuilder_.clear();
      }
      if (subscribeBuilder_ != null) {
        subscribeBuilder_.clear();
      }
      if (responseBuilder_ != null) {
        responseBuilder_.clear();
      }
      if (serviceListBuilder_ != null) {
        serviceListBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_RegistryMessage_descriptor;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.RegistryMessage getDefaultInstanceForType() {
      return tech.bobliu.rpc.proto.RegistryMessage.getDefaultInstance();
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.RegistryMessage build() {
      tech.bobliu.rpc.proto.RegistryMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.RegistryMessage buildPartial() {
      tech.bobliu.rpc.proto.RegistryMessage result = new tech.bobliu.rpc.proto.RegistryMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.bobliu.rpc.proto.RegistryMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(tech.bobliu.rpc.proto.RegistryMessage result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          registerBuilder_ != null) {
        result.payload_ = registerBuilder_.build();
      }
      if (payloadCase_ == 2 &&
          heartbeatBuilder_ != null) {
        result.payload_ = heartbeatBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          subscribeBuilder_ != null) {
        result.payload_ = subscribeBuilder_.build();
      }
      if (payloadCase_ == 4 &&
          responseBuilder_ != null) {
        result.payload_ = responseBuilder_.build();
      }
      if (payloadCase_ == 5 &&
          serviceListBuilder_ != null) {
        result.payload_ = serviceListBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.bobliu.rpc.proto.RegistryMessage) {
        return mergeFrom((tech.bobliu.rpc.proto.RegistryMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.bobliu.rpc.proto.RegistryMessage other) {
      if (other == tech.bobliu.rpc.proto.RegistryMessage.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case REGISTER: {
          mergeRegister(other.getRegister());
          break;
        }
        case HEARTBEAT: {
          mergeHeartbeat(other.getHeartbeat());
          break;
        }
        case SUBSCRIBE: {
          mergeSubscribe(other.getSubscribe());
          break;
        }
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case SERVICE_LIST: {
          mergeServiceList(other.getServiceList());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRegisterFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetHeartbeatFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetSubscribeFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetServiceListFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.RegisterRequest, tech.bobliu.rpc.proto.RegisterRequest.Builder, tech.bobliu.rpc.proto.RegisterRequestOrBuilder> registerBuilder_;
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     * @return Whether the register field is set.
     */
    @java.lang.Override
    public boolean hasRegister() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     * @return The register.
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.RegisterRequest getRegister() {
      if (registerBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (tech.bobliu.rpc.proto.RegisterRequest) payload_;
        }
        return tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return registerBuilder_.getMessage();
        }
        return tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    public Builder setRegister(tech.bobliu.rpc.proto.RegisterRequest value) {
      if (registerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        registerBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    public Builder setRegister(
        tech.bobliu.rpc.proto.RegisterRequest.Builder builderForValue) {
      if (registerBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        registerBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    public Builder mergeRegister(tech.bobliu.rpc.proto.RegisterRequest value) {
      if (registerBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance()) {
          payload_ = tech.bobliu.rpc.proto.RegisterRequest.newBuilder((tech.bobliu.rpc.proto.RegisterRequest) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          registerBuilder_.mergeFrom(value);
        } else {
          registerBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    public Builder clearRegister() {
      if (registerBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        registerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    public tech.bobliu.rpc.proto.RegisterRequest.Builder getRegisterBuilder() {
      return internalGetRegisterFieldBuilder().getBuilder();
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.RegisterRequestOrBuilder getRegisterOrBuilder() {
      if ((payloadCase_ == 1) && (registerBuilder_ != null)) {
        return registerBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (tech.bobliu.rpc.proto.RegisterRequest) payload_;
        }
        return tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.RegisterRequest register = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.RegisterRequest, tech.bobliu.rpc.proto.RegisterRequest.Builder, tech.bobliu.rpc.proto.RegisterRequestOrBuilder> 
        internalGetRegisterFieldBuilder() {
      if (registerBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = tech.bobliu.rpc.proto.RegisterRequest.getDefaultInstance();
        }
        registerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            tech.bobliu.rpc.proto.RegisterRequest, tech.bobliu.rpc.proto.RegisterRequest.Builder, tech.bobliu.rpc.proto.RegisterRequestOrBuilder>(
                (tech.bobliu.rpc.proto.RegisterRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return registerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.HeartbeatRequest, tech.bobliu.rpc.proto.HeartbeatRequest.Builder, tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder> heartbeatBuilder_;
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.HeartbeatRequest getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (tech.bobliu.rpc.proto.HeartbeatRequest) payload_;
        }
        return tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return heartbeatBuilder_.getMessage();
        }
        return tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    public Builder setHeartbeat(tech.bobliu.rpc.proto.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    public Builder setHeartbeat(
        tech.bobliu.rpc.proto.HeartbeatRequest.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    public Builder mergeHeartbeat(tech.bobliu.rpc.proto.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance()) {
          payload_ = tech.bobliu.rpc.proto.HeartbeatRequest.newBuilder((tech.bobliu.rpc.proto.HeartbeatRequest) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          heartbeatBuilder_.mergeFrom(value);
        } else {
          heartbeatBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        heartbeatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    public tech.bobliu.rpc.proto.HeartbeatRequest.Builder getHeartbeatBuilder() {
      return internalGetHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
      if ((payloadCase_ == 2) && (heartbeatBuilder_ != null)) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (tech.bobliu.rpc.proto.HeartbeatRequest) payload_;
        }
        return tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.HeartbeatRequest, tech.bobliu.rpc.proto.HeartbeatRequest.Builder, tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder> 
        internalGetHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = tech.bobliu.rpc.proto.HeartbeatRequest.getDefaultInstance();
        }
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            tech.bobliu.rpc.proto.HeartbeatRequest, tech.bobliu.rpc.proto.HeartbeatRequest.Builder, tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder>(
                (tech.bobliu.rpc.proto.HeartbeatRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return heartbeatBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.SubscribeRequest, tech.bobliu.rpc.proto.SubscribeRequest.Builder, tech.bobliu.rpc.proto.SubscribeRequestOrBuilder> subscribeBuilder_;
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     * @return Whether the subscribe field is set.
     */
    @java.lang.Override
    public boolean hasSubscribe() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     * @return The subscribe.
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.SubscribeRequest getSubscribe() {
      if (subscribeBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (tech.bobliu.rpc.proto.SubscribeRequest) payload_;
        }
        return tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return subscribeBuilder_.getMessage();
        }
        return tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    public Builder setSubscribe(tech.bobliu.rpc.proto.SubscribeRequest value) {
      if (subscribeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        subscribeBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    public Builder setSubscribe(
        tech.bobliu.rpc.proto.SubscribeRequest.Builder builderForValue) {
      if (subscribeBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        subscribeBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    public Builder mergeSubscribe(tech.bobliu.rpc.proto.SubscribeRequest value) {
      if (subscribeBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance()) {
          payload_ = tech.bobliu.rpc.proto.SubscribeRequest.newBuilder((tech.bobliu.rpc.proto.SubscribeRequest) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          subscribeBuilder_.mergeFrom(value);
        } else {
          subscribeBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    public Builder clearSubscribe() {
      if (subscribeBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        subscribeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    public tech.bobliu.rpc.proto.SubscribeRequest.Builder getSubscribeBuilder() {
      return internalGetSubscribeFieldBuilder().getBuilder();
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.SubscribeRequestOrBuilder getSubscribeOrBuilder() {
      if ((payloadCase_ == 3) && (subscribeBuilder_ != null)) {
        return subscribeBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (tech.bobliu.rpc.proto.SubscribeRequest) payload_;
        }
        return tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.SubscribeRequest subscribe = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.SubscribeRequest, tech.bobliu.rpc.proto.SubscribeRequest.Builder, tech.bobliu.rpc.proto.SubscribeRequestOrBuilder> 
        internalGetSubscribeFieldBuilder() {
      if (subscribeBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = tech.bobliu.rpc.proto.SubscribeRequest.getDefaultInstance();
        }
        subscribeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            tech.bobliu.rpc.proto.SubscribeRequest, tech.bobliu.rpc.proto.SubscribeRequest.Builder, tech.bobliu.rpc.proto.SubscribeRequestOrBuilder>(
                (tech.bobliu.rpc.proto.SubscribeRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return subscribeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.RegistryResponse, tech.bobliu.rpc.proto.RegistryResponse.Builder, tech.bobliu.rpc.proto.RegistryResponseOrBuilder> responseBuilder_;
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     * @return The response.
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.RegistryResponse getResponse() {
      if (responseBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (tech.bobliu.rpc.proto.RegistryResponse) payload_;
        }
        return tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return responseBuilder_.getMessage();
        }
        return tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    public Builder setResponse(tech.bobliu.rpc.proto.RegistryResponse value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    public Builder setResponse(
        tech.bobliu.rpc.proto.RegistryResponse.Builder builderForValue) {
      if (responseBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    public Builder mergeResponse(tech.bobliu.rpc.proto.RegistryResponse value) {
      if (responseBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance()) {
          payload_ = tech.bobliu.rpc.proto.RegistryResponse.newBuilder((tech.bobliu.rpc.proto.RegistryResponse) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          responseBuilder_.mergeFrom(value);
        } else {
          responseBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    public tech.bobliu.rpc.proto.RegistryResponse.Builder getResponseBuilder() {
      return internalGetResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.RegistryResponseOrBuilder getResponseOrBuilder() {
      if ((payloadCase_ == 4) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (tech.bobliu.rpc.proto.RegistryResponse) payload_;
        }
        return tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.RegistryResponse response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.RegistryResponse, tech.bobliu.rpc.proto.RegistryResponse.Builder, tech.bobliu.rpc.proto.RegistryResponseOrBuilder> 
        internalGetResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = tech.bobliu.rpc.proto.RegistryResponse.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            tech.bobliu.rpc.proto.RegistryResponse, tech.bobliu.rpc.proto.RegistryResponse.Builder, tech.bobliu.rpc.proto.RegistryResponseOrBuilder>(
                (tech.bobliu.rpc.proto.RegistryResponse) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();
      return responseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.ServiceList, tech.bobliu.rpc.proto.ServiceList.Builder, tech.bobliu.rpc.proto.ServiceListOrBuilder> serviceListBuilder_;
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     * @return Whether the serviceList field is set.
     */
    @java.lang.Override
    public boolean hasServiceList() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     * @return The serviceList.
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceList getServiceList() {
      if (serviceListBuilder_ == null) {
        if (payloadCase_ == 5) {
          return (tech.bobliu.rpc.proto.ServiceList) payload_;
        }
        return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
      } else {
        if (payloadCase_ == 5) {
          return serviceListBuilder_.getMessage();
        }
        return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    public Builder setServiceList(tech.bobliu.rpc.proto.ServiceList value) {
      if (serviceListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        serviceListBuilder_.setMessage(value);
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    public Builder setServiceList(
        tech.bobliu.rpc.proto.ServiceList.Builder builderForValue) {
      if (serviceListBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        serviceListBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    public Builder mergeServiceList(tech.bobliu.rpc.proto.ServiceList value) {
      if (serviceListBuilder_ == null) {
        if (payloadCase_ == 5 &&
            payload_ != tech.bobliu.rpc.proto.ServiceList.getDefaultInstance()) {
          payload_ = tech.bobliu.rpc.proto.ServiceList.newBuilder((tech.bobliu.rpc.proto.ServiceList) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 5) {
          serviceListBuilder_.mergeFrom(value);
        } else {
          serviceListBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    public Builder clearServiceList() {
      if (serviceListBuilder_ == null) {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
        }
        serviceListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    public tech.bobliu.rpc.proto.ServiceList.Builder getServiceListBuilder() {
      return internalGetServiceListFieldBuilder().getBuilder();
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceListOrBuilder getServiceListOrBuilder() {
      if ((payloadCase_ == 5) && (serviceListBuilder_ != null)) {
        return serviceListBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 5) {
          return (tech.bobliu.rpc.proto.ServiceList) payload_;
        }
        return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
      }
    }
    /**
     * <code>.registry.ServiceList service_list = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        tech.bobliu.rpc.proto.ServiceList, tech.bobliu.rpc.proto.ServiceList.Builder, tech.bobliu.rpc.proto.ServiceListOrBuilder> 
        internalGetServiceListFieldBuilder() {
      if (serviceListBuilder_ == null) {
        if (!(payloadCase_ == 5)) {
          payload_ = tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
        }
        serviceListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            tech.bobliu.rpc.proto.ServiceList, tech.bobliu.rpc.proto.ServiceList.Builder, tech.bobliu.rpc.proto.ServiceListOrBuilder>(
                (tech.bobliu.rpc.proto.ServiceList) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 5;
      onChanged();
      return serviceListBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:registry.RegistryMessage)
  }

  // @@protoc_insertion_point(class_scope:registry.RegistryMessage)
  private static final tech.bobliu.rpc.proto.RegistryMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.bobliu.rpc.proto.RegistryMessage();
  }

  public static tech.bobliu.rpc.proto.RegistryMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegistryMessage>
      PARSER = new com.google.protobuf.AbstractParser<RegistryMessage>() {
    @java.lang.Override
    public RegistryMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RegistryMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegistryMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.bobliu.rpc.proto.RegistryMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

