// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public final class Registry extends com.google.protobuf.GeneratedFile {
  private Registry() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Registry");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_RegistryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_RegistryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_ServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_ServiceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_ServiceListEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_ServiceListEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_ServiceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_ServiceList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_ServiceList_ServicesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_ServiceList_ServicesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registry_RegistryMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_registry_RegistryMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016registry.proto\022\010registry\"<\n\017RegisterRe" +
      "quest\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\017\n\007servi" +
      "ce\030\003 \001(\t\",\n\020HeartbeatRequest\022\n\n\002ip\030\001 \001(\t" +
      "\022\014\n\004port\030\002 \001(\005\"\022\n\020SubscribeRequest\"4\n\020Re" +
      "gistryResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t\"\'\n\013ServiceInfo\022\n\n\002ip\030\001 \001(\t\022\014\n\004p" +
      "ort\030\002 \001(\005\"<\n\020ServiceListEntry\022(\n\tinstanc" +
      "es\030\001 \003(\0132\025.registry.ServiceInfo\"\221\001\n\013Serv" +
      "iceList\0225\n\010services\030\001 \003(\0132#.registry.Ser" +
      "viceList.ServicesEntry\032K\n\rServicesEntry\022" +
      "\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.registry.S" +
      "erviceListEntry:\0028\001\"\214\002\n\017RegistryMessage\022" +
      "-\n\010register\030\001 \001(\0132\031.registry.RegisterReq" +
      "uestH\000\022/\n\theartbeat\030\002 \001(\0132\032.registry.Hea" +
      "rtbeatRequestH\000\022/\n\tsubscribe\030\003 \001(\0132\032.reg" +
      "istry.SubscribeRequestH\000\022.\n\010response\030\004 \001" +
      "(\0132\032.registry.RegistryResponseH\000\022-\n\014serv" +
      "ice_list\030\005 \001(\0132\025.registry.ServiceListH\000B" +
      "\t\n\007payloadB(\n\025tech.bobliu.rpc.protoP\001Z\rr" +
      "pc-server/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_registry_RegisterRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_registry_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Port", "Service", });
    internal_static_registry_HeartbeatRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_registry_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_registry_SubscribeRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_registry_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_SubscribeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_registry_RegistryResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_registry_RegistryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_RegistryResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_registry_ServiceInfo_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_registry_ServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_ServiceInfo_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_registry_ServiceListEntry_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_registry_ServiceListEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_ServiceListEntry_descriptor,
        new java.lang.String[] { "Instances", });
    internal_static_registry_ServiceList_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_registry_ServiceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_ServiceList_descriptor,
        new java.lang.String[] { "Services", });
    internal_static_registry_ServiceList_ServicesEntry_descriptor =
      internal_static_registry_ServiceList_descriptor.getNestedType(0);
    internal_static_registry_ServiceList_ServicesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_ServiceList_ServicesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_registry_RegistryMessage_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_registry_RegistryMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_registry_RegistryMessage_descriptor,
        new java.lang.String[] { "Register", "Heartbeat", "Subscribe", "Response", "ServiceList", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
