// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface RegistryMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registry.RegistryMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   * @return Whether the register field is set.
   */
  boolean hasRegister();
  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   * @return The register.
   */
  tech.bobliu.rpc.proto.RegisterRequest getRegister();
  /**
   * <code>.registry.RegisterRequest register = 1;</code>
   */
  tech.bobliu.rpc.proto.RegisterRequestOrBuilder getRegisterOrBuilder();

  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   * @return The heartbeat.
   */
  tech.bobliu.rpc.proto.HeartbeatRequest getHeartbeat();
  /**
   * <code>.registry.HeartbeatRequest heartbeat = 2;</code>
   */
  tech.bobliu.rpc.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder();

  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   * @return Whether the subscribe field is set.
   */
  boolean hasSubscribe();
  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   * @return The subscribe.
   */
  tech.bobliu.rpc.proto.SubscribeRequest getSubscribe();
  /**
   * <code>.registry.SubscribeRequest subscribe = 3;</code>
   */
  tech.bobliu.rpc.proto.SubscribeRequestOrBuilder getSubscribeOrBuilder();

  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   * @return The response.
   */
  tech.bobliu.rpc.proto.RegistryResponse getResponse();
  /**
   * <code>.registry.RegistryResponse response = 4;</code>
   */
  tech.bobliu.rpc.proto.RegistryResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   * @return Whether the serviceList field is set.
   */
  boolean hasServiceList();
  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   * @return The serviceList.
   */
  tech.bobliu.rpc.proto.ServiceList getServiceList();
  /**
   * <code>.registry.ServiceList service_list = 5;</code>
   */
  tech.bobliu.rpc.proto.ServiceListOrBuilder getServiceListOrBuilder();

  tech.bobliu.rpc.proto.RegistryMessage.PayloadCase getPayloadCase();
}
