// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface RegistryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registry.RegistryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
