// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public final class Rpc extends com.google.protobuf.GeneratedFile {
  private Rpc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Rpc");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_RpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\003rpc\"R\n\nRpcRequest\022\022\n\nreques" +
      "t_id\030\001 \001(\t\022\017\n\007service\030\002 \001(\t\022\016\n\006method\030\003 " +
      "\001(\t\022\017\n\007payload\030\004 \001(\014\"M\n\013RpcResponse\022\022\n\nr" +
      "equest_id\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\022\031\n\005erro" +
      "r\030\003 \001(\0132\n.rpc.Error\"&\n\005Error\022\014\n\004code\030\001 \001" +
      "(\005\022\017\n\007message\030\002 \001(\tB(\n\025tech.bobliu.rpc.p" +
      "rotoP\001Z\rrpc-server/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_RpcRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_rpc_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_RpcRequest_descriptor,
        new java.lang.String[] { "RequestId", "Service", "Method", "Payload", });
    internal_static_rpc_RpcResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_rpc_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_RpcResponse_descriptor,
        new java.lang.String[] { "RequestId", "Payload", "Error", });
    internal_static_rpc_Error_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_rpc_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_Error_descriptor,
        new java.lang.String[] { "Code", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
