// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>.rpc.Error error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.rpc.Error error = 3;</code>
   * @return The error.
   */
  tech.bobliu.rpc.proto.Error getError();
  /**
   * <code>.rpc.Error error = 3;</code>
   */
  tech.bobliu.rpc.proto.ErrorOrBuilder getErrorOrBuilder();
}
