// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

/**
 * Protobuf type {@code registry.ServiceListEntry}
 */
@com.google.protobuf.Generated
public final class ServiceListEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:registry.ServiceListEntry)
    ServiceListEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServiceListEntry");
  }
  // Use ServiceListEntry.newBuilder() to construct.
  private ServiceListEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServiceListEntry() {
    instances_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.bobliu.rpc.proto.ServiceListEntry.class, tech.bobliu.rpc.proto.ServiceListEntry.Builder.class);
  }

  public static final int INSTANCES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<tech.bobliu.rpc.proto.ServiceInfo> instances_;
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  @java.lang.Override
  public java.util.List<tech.bobliu.rpc.proto.ServiceInfo> getInstancesList() {
    return instances_;
  }
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends tech.bobliu.rpc.proto.ServiceInfoOrBuilder> 
      getInstancesOrBuilderList() {
    return instances_;
  }
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  @java.lang.Override
  public int getInstancesCount() {
    return instances_.size();
  }
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceInfo getInstances(int index) {
    return instances_.get(index);
  }
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceInfoOrBuilder getInstancesOrBuilder(
      int index) {
    return instances_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < instances_.size(); i++) {
      output.writeMessage(1, instances_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = instances_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(instances_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.bobliu.rpc.proto.ServiceListEntry)) {
      return super.equals(obj);
    }
    tech.bobliu.rpc.proto.ServiceListEntry other = (tech.bobliu.rpc.proto.ServiceListEntry) obj;

    if (!getInstancesList()
        .equals(other.getInstancesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInstancesCount() > 0) {
      hash = (37 * hash) + INSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getInstancesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.bobliu.rpc.proto.ServiceListEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.bobliu.rpc.proto.ServiceListEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.ServiceListEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.bobliu.rpc.proto.ServiceListEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registry.ServiceListEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registry.ServiceListEntry)
      tech.bobliu.rpc.proto.ServiceListEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.bobliu.rpc.proto.ServiceListEntry.class, tech.bobliu.rpc.proto.ServiceListEntry.Builder.class);
    }

    // Construct using tech.bobliu.rpc.proto.ServiceListEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
      } else {
        instances_ = null;
        instancesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceListEntry_descriptor;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceListEntry getDefaultInstanceForType() {
      return tech.bobliu.rpc.proto.ServiceListEntry.getDefaultInstance();
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceListEntry build() {
      tech.bobliu.rpc.proto.ServiceListEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceListEntry buildPartial() {
      tech.bobliu.rpc.proto.ServiceListEntry result = new tech.bobliu.rpc.proto.ServiceListEntry(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(tech.bobliu.rpc.proto.ServiceListEntry result) {
      if (instancesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          instances_ = java.util.Collections.unmodifiableList(instances_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instances_ = instances_;
      } else {
        result.instances_ = instancesBuilder_.build();
      }
    }

    private void buildPartial0(tech.bobliu.rpc.proto.ServiceListEntry result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.bobliu.rpc.proto.ServiceListEntry) {
        return mergeFrom((tech.bobliu.rpc.proto.ServiceListEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.bobliu.rpc.proto.ServiceListEntry other) {
      if (other == tech.bobliu.rpc.proto.ServiceListEntry.getDefaultInstance()) return this;
      if (instancesBuilder_ == null) {
        if (!other.instances_.isEmpty()) {
          if (instances_.isEmpty()) {
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstancesIsMutable();
            instances_.addAll(other.instances_);
          }
          onChanged();
        }
      } else {
        if (!other.instances_.isEmpty()) {
          if (instancesBuilder_.isEmpty()) {
            instancesBuilder_.dispose();
            instancesBuilder_ = null;
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
            instancesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetInstancesFieldBuilder() : null;
          } else {
            instancesBuilder_.addAllMessages(other.instances_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tech.bobliu.rpc.proto.ServiceInfo m =
                  input.readMessage(
                      tech.bobliu.rpc.proto.ServiceInfo.parser(),
                      extensionRegistry);
              if (instancesBuilder_ == null) {
                ensureInstancesIsMutable();
                instances_.add(m);
              } else {
                instancesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<tech.bobliu.rpc.proto.ServiceInfo> instances_ =
      java.util.Collections.emptyList();
    private void ensureInstancesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        instances_ = new java.util.ArrayList<tech.bobliu.rpc.proto.ServiceInfo>(instances_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        tech.bobliu.rpc.proto.ServiceInfo, tech.bobliu.rpc.proto.ServiceInfo.Builder, tech.bobliu.rpc.proto.ServiceInfoOrBuilder> instancesBuilder_;

    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public java.util.List<tech.bobliu.rpc.proto.ServiceInfo> getInstancesList() {
      if (instancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instances_);
      } else {
        return instancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public int getInstancesCount() {
      if (instancesBuilder_ == null) {
        return instances_.size();
      } else {
        return instancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceInfo getInstances(int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);
      } else {
        return instancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder setInstances(
        int index, tech.bobliu.rpc.proto.ServiceInfo value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.set(index, value);
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder setInstances(
        int index, tech.bobliu.rpc.proto.ServiceInfo.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.set(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder addInstances(tech.bobliu.rpc.proto.ServiceInfo value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder addInstances(
        int index, tech.bobliu.rpc.proto.ServiceInfo value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(index, value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder addInstances(
        tech.bobliu.rpc.proto.ServiceInfo.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder addInstances(
        int index, tech.bobliu.rpc.proto.ServiceInfo.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder addAllInstances(
        java.lang.Iterable<? extends tech.bobliu.rpc.proto.ServiceInfo> values) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instances_);
        onChanged();
      } else {
        instancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder clearInstances() {
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        instancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public Builder removeInstances(int index) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.remove(index);
        onChanged();
      } else {
        instancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceInfo.Builder getInstancesBuilder(
        int index) {
      return internalGetInstancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceInfoOrBuilder getInstancesOrBuilder(
        int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);  } else {
        return instancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public java.util.List<? extends tech.bobliu.rpc.proto.ServiceInfoOrBuilder> 
         getInstancesOrBuilderList() {
      if (instancesBuilder_ != null) {
        return instancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instances_);
      }
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceInfo.Builder addInstancesBuilder() {
      return internalGetInstancesFieldBuilder().addBuilder(
          tech.bobliu.rpc.proto.ServiceInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceInfo.Builder addInstancesBuilder(
        int index) {
      return internalGetInstancesFieldBuilder().addBuilder(
          index, tech.bobliu.rpc.proto.ServiceInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .registry.ServiceInfo instances = 1;</code>
     */
    public java.util.List<tech.bobliu.rpc.proto.ServiceInfo.Builder> 
         getInstancesBuilderList() {
      return internalGetInstancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        tech.bobliu.rpc.proto.ServiceInfo, tech.bobliu.rpc.proto.ServiceInfo.Builder, tech.bobliu.rpc.proto.ServiceInfoOrBuilder> 
        internalGetInstancesFieldBuilder() {
      if (instancesBuilder_ == null) {
        instancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            tech.bobliu.rpc.proto.ServiceInfo, tech.bobliu.rpc.proto.ServiceInfo.Builder, tech.bobliu.rpc.proto.ServiceInfoOrBuilder>(
                instances_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        instances_ = null;
      }
      return instancesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:registry.ServiceListEntry)
  }

  // @@protoc_insertion_point(class_scope:registry.ServiceListEntry)
  private static final tech.bobliu.rpc.proto.ServiceListEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.bobliu.rpc.proto.ServiceListEntry();
  }

  public static tech.bobliu.rpc.proto.ServiceListEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceListEntry>
      PARSER = new com.google.protobuf.AbstractParser<ServiceListEntry>() {
    @java.lang.Override
    public ServiceListEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServiceListEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceListEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceListEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

