// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface ServiceListEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registry.ServiceListEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  java.util.List<tech.bobliu.rpc.proto.ServiceInfo> 
      getInstancesList();
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  tech.bobliu.rpc.proto.ServiceInfo getInstances(int index);
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  java.util.List<? extends tech.bobliu.rpc.proto.ServiceInfoOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .registry.ServiceInfo instances = 1;</code>
   */
  tech.bobliu.rpc.proto.ServiceInfoOrBuilder getInstancesOrBuilder(
      int index);
}
