// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

@com.google.protobuf.Generated
public interface ServiceListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registry.ServiceList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  int getServicesCount();
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  boolean containsServices(
      java.lang.String key);
  /**
   * Use {@link #getServicesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
  getServices();
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
  getServicesMap();
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry getServicesOrDefault(
      java.lang.String key,
      /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry defaultValue);
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  tech.bobliu.rpc.proto.ServiceListEntry getServicesOrThrow(
      java.lang.String key);
}
