// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: registry.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto;

/**
 * Protobuf type {@code registry.ServiceList}
 */
@com.google.protobuf.Generated
public final class ServiceList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:registry.ServiceList)
    ServiceListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ServiceList");
  }
  // Use ServiceList.newBuilder() to construct.
  private ServiceList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServiceList() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetServices();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.bobliu.rpc.proto.ServiceList.class, tech.bobliu.rpc.proto.ServiceList.Builder.class);
  }

  public static final int SERVICES_FIELD_NUMBER = 1;
  private static final class ServicesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>newDefaultInstance(
                tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_ServicesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                tech.bobliu.rpc.proto.ServiceListEntry.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> services_;
  private com.google.protobuf.MapField<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
  internalGetServices() {
    if (services_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ServicesDefaultEntryHolder.defaultEntry);
    }
    return services_;
  }
  public int getServicesCount() {
    return internalGetServices().getMap().size();
  }
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  @java.lang.Override
  public boolean containsServices(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetServices().getMap().containsKey(key);
  }
  /**
   * Use {@link #getServicesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> getServices() {
    return getServicesMap();
  }
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> getServicesMap() {
    return internalGetServices().getMap();
  }
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry getServicesOrDefault(
      java.lang.String key,
      /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> map =
        internalGetServices().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
   */
  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceListEntry getServicesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> map =
        internalGetServices().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetServices(),
        ServicesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> entry
         : internalGetServices().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
      services__ = ServicesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, services__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.bobliu.rpc.proto.ServiceList)) {
      return super.equals(obj);
    }
    tech.bobliu.rpc.proto.ServiceList other = (tech.bobliu.rpc.proto.ServiceList) obj;

    if (!internalGetServices().equals(
        other.internalGetServices())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetServices().getMap().isEmpty()) {
      hash = (37 * hash) + SERVICES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetServices().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static tech.bobliu.rpc.proto.ServiceList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static tech.bobliu.rpc.proto.ServiceList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static tech.bobliu.rpc.proto.ServiceList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.bobliu.rpc.proto.ServiceList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registry.ServiceList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registry.ServiceList)
      tech.bobliu.rpc.proto.ServiceListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetServices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableServices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.bobliu.rpc.proto.ServiceList.class, tech.bobliu.rpc.proto.ServiceList.Builder.class);
    }

    // Construct using tech.bobliu.rpc.proto.ServiceList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableServices().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.bobliu.rpc.proto.Registry.internal_static_registry_ServiceList_descriptor;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceList getDefaultInstanceForType() {
      return tech.bobliu.rpc.proto.ServiceList.getDefaultInstance();
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceList build() {
      tech.bobliu.rpc.proto.ServiceList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceList buildPartial() {
      tech.bobliu.rpc.proto.ServiceList result = new tech.bobliu.rpc.proto.ServiceList(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(tech.bobliu.rpc.proto.ServiceList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.services_ = internalGetServices().build(ServicesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.bobliu.rpc.proto.ServiceList) {
        return mergeFrom((tech.bobliu.rpc.proto.ServiceList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.bobliu.rpc.proto.ServiceList other) {
      if (other == tech.bobliu.rpc.proto.ServiceList.getDefaultInstance()) return this;
      internalGetMutableServices().mergeFrom(
          other.internalGetServices());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
              services__ = input.readMessage(
                  ServicesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableServices().ensureBuilderMap().put(
                  services__.getKey(), services__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ServicesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder, tech.bobliu.rpc.proto.ServiceListEntry> {
      @java.lang.Override
      public tech.bobliu.rpc.proto.ServiceListEntry build(tech.bobliu.rpc.proto.ServiceListEntryOrBuilder val) {
        if (val instanceof tech.bobliu.rpc.proto.ServiceListEntry) { return (tech.bobliu.rpc.proto.ServiceListEntry) val; }
        return ((tech.bobliu.rpc.proto.ServiceListEntry.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> defaultEntry() {
        return ServicesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ServicesConverter servicesConverter = new ServicesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder, tech.bobliu.rpc.proto.ServiceListEntry, tech.bobliu.rpc.proto.ServiceListEntry.Builder> services_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder, tech.bobliu.rpc.proto.ServiceListEntry, tech.bobliu.rpc.proto.ServiceListEntry.Builder>
        internalGetServices() {
      if (services_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(servicesConverter);
      }
      return services_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder, tech.bobliu.rpc.proto.ServiceListEntry, tech.bobliu.rpc.proto.ServiceListEntry.Builder>
        internalGetMutableServices() {
      if (services_ == null) {
        services_ = new com.google.protobuf.MapFieldBuilder<>(servicesConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return services_;
    }
    public int getServicesCount() {
      return internalGetServices().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    @java.lang.Override
    public boolean containsServices(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetServices().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getServicesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> getServices() {
      return getServicesMap();
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> getServicesMap() {
      return internalGetServices().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry getServicesOrDefault(
        java.lang.String key,
        /* nullable */
tech.bobliu.rpc.proto.ServiceListEntry defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder> map = internalGetMutableServices().ensureBuilderMap();
      return map.containsKey(key) ? servicesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    @java.lang.Override
    public tech.bobliu.rpc.proto.ServiceListEntry getServicesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder> map = internalGetMutableServices().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return servicesConverter.build(map.get(key));
    }
    public Builder clearServices() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableServices().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    public Builder removeServices(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableServices().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry>
        getMutableServices() {
      bitField0_ |= 0x00000001;
      return internalGetMutableServices().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    public Builder putServices(
        java.lang.String key,
        tech.bobliu.rpc.proto.ServiceListEntry value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableServices().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    public Builder putAllServices(
        java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> values) {
      for (java.util.Map.Entry<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntry> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableServices().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .registry.ServiceListEntry&gt; services = 1;</code>
     */
    public tech.bobliu.rpc.proto.ServiceListEntry.Builder putServicesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, tech.bobliu.rpc.proto.ServiceListEntryOrBuilder> builderMap = internalGetMutableServices().ensureBuilderMap();
      tech.bobliu.rpc.proto.ServiceListEntryOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = tech.bobliu.rpc.proto.ServiceListEntry.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof tech.bobliu.rpc.proto.ServiceListEntry) {
        entry = ((tech.bobliu.rpc.proto.ServiceListEntry) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (tech.bobliu.rpc.proto.ServiceListEntry.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:registry.ServiceList)
  }

  // @@protoc_insertion_point(class_scope:registry.ServiceList)
  private static final tech.bobliu.rpc.proto.ServiceList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.bobliu.rpc.proto.ServiceList();
  }

  public static tech.bobliu.rpc.proto.ServiceList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceList>
      PARSER = new com.google.protobuf.AbstractParser<ServiceList>() {
    @java.lang.Override
    public ServiceList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServiceList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.bobliu.rpc.proto.ServiceList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

