// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/user_service.proto
// Protobuf Java Version: 4.34.1

package tech.bobliu.rpc.proto.example;

@com.google.protobuf.Generated
public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
